[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://qh6hjtm8-3001.inc1.devtunnels.ms"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
