-- 081: Frozen per-node Claude/fallback rankings
--
-- The dynamic Day1-7 email templates need a "ranking" (which products to show,
-- in what order) generated by Claude. Without persistence, preview and the actual
-- send could call Claude separately and produce DIFFERENT content.
--
-- This table freezes the ranking ONCE per (journey, node, ranking_type). The first
-- touch (preview OR send OR prewarm) computes it and stores it here; every read
-- after — preview, all worker sends, refresh, restart — returns the SAME frozen
-- ranking. Guarantees preview == sent email, and Claude is called once per node.
--
-- ranking_type:
--   'welcome' | 'cruise' | 'visa' | 'holidays' | 'activities'  (one per node)
--   'destination_<key>'  for Day6 (one per destination, e.g. destination_bali)
-- source: 'claude' | 'fallback' | 'fallback_no_api_key'

CREATE TABLE IF NOT EXISTS journey_node_rankings (
  id            BIGSERIAL PRIMARY KEY,
  journey_id    BIGINT NOT NULL,
  node_id       TEXT   NOT NULL,
  ranking_type  TEXT   NOT NULL,
  ranking       JSONB  NOT NULL,
  source        TEXT,
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

-- One frozen ranking per (journey, node, type). ON CONFLICT in the app dedupes
-- concurrent first-writers so all workers for a node share the same ranking.
ALTER TABLE journey_node_rankings DROP CONSTRAINT IF EXISTS jnr_unique;
ALTER TABLE journey_node_rankings ADD CONSTRAINT jnr_unique UNIQUE (journey_id, node_id, ranking_type);

CREATE INDEX IF NOT EXISTS idx_jnr_journey_node ON journey_node_rankings(journey_id, node_id);
