/**
 * Day2CruiseRenderer
 *
 * Pure renderer for the Day-2 cruise email. Takes the data.json shape produced
 * by Day2CruiseDataService and a template HTML string, produces the final HTML
 * ready for EmailChannel.send.
 *
 * Block-injection design:
 *   - 5 scalar placeholders (HERO_BG_IMAGE, HERO_TITLE, HERO_DESCRIPTION,
 *     REGIONAL_SUBTITLE, REGIONAL_TITLE)
 *   - 4 HTML blocks (CITY_ROWS, SAVER_PACKAGE_ROWS, REGIONAL_CRUISE_ROWS,
 *     CRUISE_LINE_ROWS) generated by the helpers below.
 *
 * Faithful port of the team's generate-email.js, with two minor fixes:
 *   1. Cities-grid: fixes a doubled spacer-row that appeared between the last
 *      regular pair and a trailing full-width card.
 *   2. Cities-grid: avoids leaving a `<tr>` orphaned when a full-width card
 *      lands after an unclosed regular row.
 */

import { readFileSync } from 'node:fs';

// ── card builders ─────────────────────────────────────────────────────────

function generateCityRows(cities) {
  let html = `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="width: 100%; border-collapse: collapse">`;

  let rowOpen = false;
  for (let i = 0; i < cities.length; i++) {
    const city = cities[i];
    const isFullWidth = !!city.is_full_width;

    if (isFullWidth) {
      // Close any open 2-col row before emitting a full-width row.
      if (rowOpen) { html += `</tr>`; rowOpen = false; }
      // Spacer between previous content and the full-width card.
      if (i > 0) {
        html += `<tr><td colspan="2" style="height: 12px; line-height: 12px; font-size: 12px;">&nbsp;</td></tr>`;
      }
      html += `<tr><td class="city-col city-col-last" colspan="2" valign="top" style="padding: 0;">
                  <a href="${city.link}" style="display: block; text-decoration: none; border: 1px solid #e2ddd6; background-color: #fdfcf9; padding: 11px 12px;">
                    <div style="font-size: 0; line-height: 0">
                      <span style="display: inline-block; width: 5%; vertical-align: middle;"><img src="${city.flag_url}" alt="${city.flag_alt}" width="20" height="20" style="display: block; width: 20px; height: 20px; border: 0"/></span>
                      <span style="display: inline-block; width: 70%; vertical-align: middle; font-family: Georgia, serif; margin-left: 20px;">
                        <div style="font-size: 13px; line-height: 15px; color: #1a1a1a; font-weight: 700;">${city.name}</div>
                        <div style="font-size: 9px; line-height: 13px; color: #b6b6b6;">${city.sub_text}</div>
                      </span>
                      <span style="display: inline-block; width: 15%; vertical-align: middle; text-align: right; font-family: Georgia, serif; font-size: 12px; color: #1a1a1a;">&#8594;</span>
                    </div>
                  </a>
                </td></tr>`;
      continue;
    }

    // Regular 2-col card.
    if (!rowOpen) { html += `<tr>`; rowOpen = true; }

    const isLeftCol = !rowOpen ? true : (i % 2 === 0); // safety guard
    // Determine padding side based on whether this card sits in the left or right cell of a row
    // Simpler: track a column index per row instead of relying on parity.
    // Compute cellsInThisRow by counting non-full-width consecutive cards, but for simplicity
    // we rely on the fact that we open <tr> for the first non-full card and close on the second.
    const padding = isLeftCol ? 'padding-right: 6px;' : 'padding-left: 6px;';

    html += `<td class="city-col" width="50%" valign="top" style="width: 50%; padding-top: 0; ${padding} padding-bottom: 0;">
                <a href="${city.link}" style="display: block; text-decoration: none;">
                  <table role="presentation" width="100%" height="68" cellpadding="0" cellspacing="0" border="0" style="width: 100%; height: 68px; border: 1px solid #e2ddd6; background-color: #fdfcf9; border-collapse: separate;">
                    <tr>
                      <td valign="middle" style="padding: 10px 12px;">
                        <div style="font-size: 0; line-height: 0">
                          <span style="display: inline-block; width: 10%; vertical-align: middle;"><img src="${city.flag_url}" alt="${city.flag_alt}" width="20" height="20" style="display: block; width: 20px; height: 20px; border: 0"/></span>
                          <span style="display: inline-block; width: 65%; vertical-align: middle; font-family: Georgia, serif; margin-left: 20px;">
                            <div style="font-size: 13px; line-height: 15px; color: #1a1a1a; font-weight: 700;">${city.name}</div>
                            <div style="font-size: 9px; line-height: 13px; color: #b6b6b6;">${city.sub_text}</div>
                          </span>
                          <span style="display: inline-block; width: 10%; vertical-align: middle; text-align: right; font-family: Georgia, serif; font-size: 12px; color: #1a1a1a;">&#8594;</span>
                        </div>
                      </td>
                    </tr>
                  </table>
                </a>
              </td>`;

    // Close the row after the second card OR if this is the last item.
    const nextIsFullWidth = i + 1 < cities.length && cities[i + 1].is_full_width;
    const closeRow = (i % 2 === 1) || (i === cities.length - 1) || nextIsFullWidth;
    if (closeRow) {
      // If we only put a single card in this row (e.g., last item is right-padded),
      // pad with an empty cell so the row closes cleanly.
      if (i % 2 === 0) html += `<td width="50%">&nbsp;</td>`;
      html += `</tr>`;
      rowOpen = false;

      // Spacer between this row and the next, unless next is full-width
      // (the full-width branch will emit its own leading spacer) or this is the last card.
      const isLast = i === cities.length - 1;
      if (!isLast && !nextIsFullWidth) {
        html += `<tr><td colspan="2" style="height: 12px; line-height: 12px; font-size: 12px;">&nbsp;</td></tr>`;
      }
    }
  }

  html += `</table>`;
  return html;
}

function generateSaverPackageRows(packages) {
  let html = '';
  packages.forEach(pkg => {
    html += `
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="width: 100%; border-collapse: collapse; border: 1px solid #eeeae4; margin-bottom: 18px;">
      <tr>
        <td class="saver-img-col" width="140" valign="top" style="display: table-cell; width: 140px; padding: 0;">
          <img class="saver-img" src="${pkg.image}" alt="${pkg.title}" width="140" height="140" style="display: block; width: 140px; height: 140px; border: 0;"/>
        </td>
        <td class="saver-content-col" valign="top" style="display: table-cell; padding: 14px 16px; font-family: Georgia, serif;">
          <div>
            <span style="display: block; font-size: 10px; line-height: 14px; color: #1a1a1a; letter-spacing: 2px; text-transform: uppercase; font-weight: 700; padding-bottom: 4px;">${pkg.region}</span>
            <span style="display: block; font-family: Georgia, serif; font-size: 17px; line-height: 24px; color: #1a1a1a; font-weight: 400; padding-bottom: 6px;">${pkg.title}</span>
            <span style="display: block; font-size: 12px; line-height: 18px; color: #777777;">${pkg.description}</span>
          </div>
        </td>
        <td class="saver-price-col" width="170" valign="middle" align="center" style="display: table-cell; width: 170px; min-width: 170px; background-color: #fafaf8; border-left: 1px solid #eeeae4; padding: 14px 12px; font-family: Georgia, serif;">
          <div>
            <span style="display: block; font-size: 11px; line-height: 16px; color: #b8b8b8; text-transform: uppercase; letter-spacing: 1.8px; font-weight: 700; padding-bottom: 4px;">Starting From</span>
            <span style="display: block; font-family: Georgia, serif; font-size: 17px; line-height: 22px; color: #1a1a1a; font-weight: 400; padding-bottom: 2px;">${pkg.price}</span>
            <span style="display: block; font-size: 13px; line-height: 18px; color: #8e8e8e; padding-bottom: 10px;">per person</span>
            <a href="${pkg.link}" style="display: inline-block; font-family: Georgia, serif; font-size: 11px; line-height: 16px; color: #ffffff; font-weight: 700; letter-spacing: 1px; white-space: nowrap; text-transform: uppercase; text-decoration: none; background-color: #1a1a1a; border: 1px solid #1a1a1a; padding: 10px 16px;">Book Now &#8594;</a>
          </div>
        </td>
      </tr>
    </table>`;
  });
  return html;
}

function generateRegionalCruiseRows(regionalData) {
  let html = `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="width: 100%; border-collapse: collapse">`;
  const items = regionalData.items;

  for (let i = 0; i < items.length; i += 2) {
    html += `<tr>`;
    for (let j = 0; j < 2; j++) {
      const index = i + j;
      if (index < items.length) {
        const item = items[index];
        const padding = (j === 0) ? 'padding-right: 6px;' : 'padding-left: 6px;';
        html += `
        <td class="med-col med-card-gap" width="50%" valign="top" height="1" style="width: 50%; padding-top: 0; ${padding} padding-bottom: 14px;">
          <table role="presentation" width="100%" height="100%" cellpadding="0" cellspacing="0" border="0" style="width: 100%; height: 100%; border: 1px solid #ece7df; background-color: #f8f6f2; border-radius: 6px; border-collapse: separate; overflow: hidden;">
            <tr>
              <td valign="top" height="175" style="padding: 0; height: 175px;">
                <img class="med-img" src="${item.image}" alt="${item.title}" width="100%" style="display: block; width: 100%; height: 175px; border: 0; border-top-left-radius: 6px; border-top-right-radius: 6px; object-fit: cover;"/>
              </td>
            </tr>
            <tr>
              <td valign="top" height="180" style="padding: 17px 16px 12px; font-family: Georgia, serif; height: 180px;">
                <div style="display: inline-block; font-size: 10px; line-height: 12px; letter-spacing: 1.5px; text-transform: uppercase; color: #7f7f7f; font-weight: 700; background-color: #efebe5; border-radius: 10px; padding: 3px 8px;">${item.tag}</div>
                <div style="font-family: Georgia, serif; font-size: 20px; line-height: 26px; color: #1a1a1a; font-weight: 700; padding-top: 8px; padding-bottom: 8px;">${item.title}</div>
                <div style="font-size: 12px; line-height: 18px; color: #888888; padding-bottom: 0;">${item.description}</div>
              </td>
            </tr>
            <tr>
              <td valign="bottom" height="1" style="padding: 0 16px 16px; height: 1px;">
                <a href="${item.link}" style="display: block; width: 100%; background-color: #1a1a1a; border: 1px solid #1a1a1a; font-family: Georgia, serif; font-size: 11px; line-height: 14px; color: #ffffff; font-weight: 700; letter-spacing: 2px; text-transform: uppercase; text-decoration: none; text-align: center; padding: 11px 12px; box-sizing: border-box;">View Itinerary &#8594;</a>
              </td>
            </tr>
          </table>
        </td>`;
      } else {
        html += `<td width="50%">&nbsp;</td>`;
      }
    }
    html += `</tr>`;
  }

  html += `</table>`;
  return html;
}

function generateCruiseLineRows(cruiseLines) {
  let html = `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="width: 100%; border-collapse: collapse">`;

  for (let i = 0; i < cruiseLines.length; i += 2) {
    html += `<tr>`;
    for (let j = 0; j < 2; j++) {
      const index = i + j;
      if (index < cruiseLines.length) {
        const line = cruiseLines[index];
        const padding = (j === 0) ? 'padding-right: 6px;' : 'padding-left: 6px;';
        html += `
        <td class="cruise-col" width="50%" valign="top" style="display: table-cell; width: 50%; padding-top: 0; ${padding} padding-bottom: 12px;">
          <a href="${line.link}" style="display: block; text-decoration: none">
            <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="width: 100%; border-collapse: collapse; border: 1px solid #e8e4de; background-color: #ffffff;">
              <tr><td><img class="fleet-img" src="${line.image}" alt="${line.name}" width="100%" height="165" style="display: block; width: 100%; height: 165px; border: 0; object-fit: cover;"/></td></tr>
              <tr>
                <td height="74" style="padding: 12px; height: 74px;">
                  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="width: 100%; border-collapse: collapse;">
                    <tr>
                      <td align="left" valign="middle" style="font-family: Georgia, serif;">
                        <div class="cruise-title-size" style="font-size: 20px; line-height: 24px; color: #1a1a1a; font-weight: 700; padding-bottom: 4px;">${line.name}</div>
                        <div style="font-size: 11px; line-height: 16px; color: #888888;">${line.destinations}</div>
                      </td>
                      <td width="32" align="right" valign="middle" style="padding-left: 8px;">
                        <table role="presentation" width="32" cellpadding="0" cellspacing="0" border="0" style="width: 32px; border-collapse: collapse;">
                          <tr><td align="center" valign="middle" bgcolor="#f2f2f2" style="background-color: #f2f2f2; width: 32px; height: 32px; border-radius: 16px; font-family: Georgia, serif; font-size: 16px; line-height: 16px; color: #1a1a1a;">&#8594;</td></tr>
                        </table>
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>
            </table>
          </a>
        </td>`;
      } else {
        html += `<td width="50%">&nbsp;</td>`;
      }
    }
    html += `</tr>`;
  }

  html += `</table>`;
  return html;
}

// ── public API ────────────────────────────────────────────────────────────

/**
 * Render the Day-2 cruise email HTML.
 * @param {string|object} templateOrPath  HTML template string OR a path to one
 * @param {object}         data            data.json shape (see Day2CruiseDataService)
 * @returns {string} fully-rendered HTML
 */
export function renderDay2Cruise(templateOrPath, data) {
  const template = templateOrPath.includes('<')
    ? templateOrPath
    : readFileSync(templateOrPath, 'utf8');

  let html = template;
  html = html.split('{{HERO_BG_IMAGE}}').join(data.hero.bg_image);
  html = html.split('{{HERO_TITLE}}').join(data.hero.title);
  html = html.split('{{HERO_DESCRIPTION}}').join(data.hero.description);
  html = html.split('{{CITY_ROWS}}').join(generateCityRows(data.departure_cities));
  html = html.split('{{SAVER_PACKAGE_ROWS}}').join(generateSaverPackageRows(data.saver_packages));
  html = html.split('{{REGIONAL_TITLE}}').join(data.regional_cruises.section_title);
  html = html.split('{{REGIONAL_SUBTITLE}}').join(data.regional_cruises.section_subtitle);
  html = html.split('{{REGIONAL_CRUISE_ROWS}}').join(generateRegionalCruiseRows(data.regional_cruises));
  html = html.split('{{CRUISE_LINE_ROWS}}').join(generateCruiseLineRows(data.cruise_lines));

  return html;
}

export const _internals = {
  generateCityRows, generateSaverPackageRows,
  generateRegionalCruiseRows, generateCruiseLineRows,
};

export default renderDay2Cruise;
